# Generated by Django 4.2.5 on 2024-01-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_contact_number_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='productfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_imagemin1',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_imagemin2',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_imagemin3',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
    ]
