# Generated by Django 4.2.5 on 2024-01-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_product_image_product_product_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_imagemin4',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ram', 'Ram se Ram Tak'), ('Paas', 'Paas Jab Se Tum Nahi'), ('Hind', 'Hind Ki Awaz'), ('Ek', 'Ek Radha Geet Gati Hai')], max_length=10),
        ),
    ]
